export default function Page() {
  return (
    <div>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
      <p>Dashboard Page</p>
    </div>
  );
}